# Site settings
title: Andrew Kamal | Tech Enthusiast | Copt
description: "I build technologies for startups, follow my educational journey"
baseurl: ""
url: ""

# User settings
username: Mentors4EDU
user_title: Andrew Kamal
twitter_username: gamer456148
github_username:  Mentors4EDU
linkedin_public_url: gamer456148
# disqus_username: loremipsum
profile_picture: https://avatars1.githubusercontent.com/u/12502053?s=460&u=03c9ac7a9cc80999e8255ae1a7970575a7c1e356&v=4.png

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: http://www.github.com/Mentors4EDU
      new_tab: true
      key_trigger: g
    - title: twitter
      url: http://www.twitter.com/gamer456148
      key_trigger: t
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
Education:
  - name: Mentors4EDU
    url: https://www.edustudio.org
  - name: Quantum Academy
    url: https://quantacademy.blogspot.com/ 
Healthcare: 
  - name: Bleunomics
    url: https://bleunomics.com
  - name: OrgDes Labs
    url: https://www.linkedin.com/showcase/orgdes-labs
  - name: HipaaSafe2.0
    url: https://www.starkdrones.org/home/os#h.p_SUnfzfkBJFC3   
  - name: IntelliRadiology
    url: https://github.com/AIRadiology       
  - name: Coronavirus Tools
    url: https://cov19.github.io/
  - name: EldSuit Innovations 
    url: https://github.com/eldsuit-innovations
Entertainment:     
  - name: FilmVestor
    url: https://devpost.com/software/filmvestor
  - name: The NonVisibles
    url: https://www.crunchbase.com/organization/the-nonvisibles
  - name: Gamelectual Studios
    url: https://activity.games
  - name: St. George the Iron Soldier
    url: https://www.slated.com/films/451133/
  - name: AndSocialREW Gaming and Publishing
    url: https://www.crunchbase.com/organization/andsocialrew-gaming-and-publishing 
Food Delivery:
  - name: NohVoo
    url: https://www.crunchbase.com/organization/nohvoo
  - name: QP Foods
    url: https://www.crunchbase.com/organization/qp-foods-calorie-search-delivery        
  - name: SnackRunner
    url: https://www.crunchbase.com/organization/snackrunner
Environmental Tech:
  - name: CoolCoil
    url: https://www.crunchbase.com/organization/coolcoil 
  - name: Stark Drones
    url: https://www.starkdrones.org
  - name: Water4ThePeople
    url: https://www.crunchbase.com/organization/water4thepeople  
  - name: AMKOU Aeronautics GP
    url: https://www.crunchbase.com/organization/amkou-aeronautics-gp
  - name: SolarFuel Transportation
    url: http://www.solarfuel.us/
E-Commerce Projects:
  - name: HopePay
    url: https://github.com/Mentors4EDU/HopePay-App-Portal
  - name: TapRocket
    url: https://taprocket.net
  - name: DealsGhost
    url: https://www.crunchbase.com/organization/dealsghost
  - name: AMKUPFashion
    url: https://www.crunchbase.com/organization/amkupfashion    
 Blockchain Projects:
  - name: WeCrypto
    url: http://wecrypto.net  
  - name: DigiBike
    url: https://www.crunchbase.com/organization/digibike   
  - name: BlockFilm
    url: https://www.starkdrones.org/home/os#h.p_cXiUaElgu0I1   
  - name: Chainterra
    url: https://www.chainterra.com/   
  - name: ChainBoard
    url: https://www.kickstarter.com/projects/quantumphysics/chainboard-the-next-gen-wireless-dev-board
  - name: BlockStar Labs
    url: https://www.crunchbase.com/organization/blockstar-labs    
  - name: StartHub Messenger
    url: https://www.crunchbase.com/organization/starthub-messenger
  - name: The Next Big NFT Collective
    url: https://mentors4edu.github.io/NFTs/
Cryptocurrency Projects:
  - name: AMKN
    url: https://https://bitclout.com/u/AMKN
  - name: Lonero
    url: https://lonero.org/
  - name: BitToken
    url: https://github.com/Mentors4EDU/BitToken    
  - name: FilmClout
    url: http://filmclout.net/    
  - name: CloutPool
    url: https://cloutpool.net
  - name: CloutLock
    url: http://cloutlock.net/   
  - name: MatchPay
    url: https://github.com/Mentors4EDU/MatchPay
  - name: PeerSocial
    url: https://www.crunchbase.com/organization/peersocial
  - name: SpaceClout
    url: https://spaceclout.github.io/    
  - name: BitBadges
    url: https://bitbadges.web.app    
  - name: CrowdCoin
    url: https://github.com/CrowdCoin-Team    
  - name: EtherStone
    url: https://etherstone.org    
  - name: CloutWorld
    url: https://bitclout.com/u/CloutWorld
  - name: Cloutathon
    url: https://cloutathon.com/
  - name: CloutContracts
    url: https://cloutcontracts.net
 Philosophy / Other Projects:
  - name: Armenia
    url: https://armenia.substack.com/
  - name: Startup Tools
    url: https://mentors4edu.github.io/Startup-Tools/      
  - name: OpenFranchise
    url: https://open-franchise.github.io  
  - name: The Bible Project
    url: https://www.minds.com/bibleproject/        
  - name: Future Web Standards
    url: https://starkdrones.github.io/Future-Web-Standards/
  - name: Open Innovation License
    url: https://github.com/StarkDrones/OPNL     
  - name: The Intellectualism Party
    url: https://www.volunteermatch.org/search/org1189644.jsp
  - name: Andrew Kamal for Michigan 8th District Senate
    url: https://ballotpedia.org/Andrew_Kamal    
Cryptocurrency Proposals:
  - name: BISQ Social Trading
    url: https://github.com/bisq-network/proposals/issues/332    
  - name: Offline-Centered TheNewBoston
    url: https://github.com/thenewboston-developers/Projects/issues/184  
  - name: Bitcoin Efficient (Proof of Computation)
    url: https://lonero.org/pocp.html    
  - name: Privacy-Focused BLE and NFC Gateway for TNB
    url: https://github.com/thenewboston-developers/Projects/issues/187
Consulting or Firms or Studios: 
  - name: DigitalCPR
    url: https://www.digitalcpr.net/    
  - name: QuantPortal
    url: https:/aiqaunt.co    
  - name: The Startup Patriots
    url: https://www.crunchbase.com/organization/the-startup-patriots
      
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
